GCSOFT.MVC.Web/Areas/Administrator/Controllers/SysAuthenticationController.cs
using System.Web.Mvc;
using System.Collections.Generic;
using System.Linq;
using GCSOFT.MVC.Service.SystemService.Interface;
using GCSOFT.MVC.Web.Helper;
using GCSOFT.MVC.Web.Helper.ActionFilters;
using GCSOFT.MVC.Model.SystemModels;
using System.Text;
using GCSOFT.MVC.Web.ViewModels;
using GCSOFT.MVC.Web.ViewModels.SystemViewModels.HT_CongViecVaVuViec;

namespace GCSOFT.MVC.Web.Areas.Administrator.Controllers
{
	[CompressResponseAttribute]
    public class SysAuthenticationController : BaseController
    {
        #region -- Properties --
        private readonly IUserGroupService _userGrpServices;
        private readonly ICongViecService _congViecServices;
        private readonly IVuViecService _vuViecService;
        private readonly IAuthenticationService _authenServices;
        private readonly ICongViecVaVuViecService _congViecVaVuViecService;

        private IEnumerable<Permission> permissions = null;
        private HT_NhomUser userGroup;
        private StringBuilder buildTree;
        private string sysCategory = "UG";
        private bool? permisson;
        #endregion

        #region -- Contructor --
        public SysAuthenticationController
            (
                IVuViecService vuViecService
                , ICongViecService congViecServices
                , IUserGroupService userGrpServices
                , IAuthenticationService authenServices
                , ICongViecVaVuViecService congViecVaVuViecService
            ) : base(vuViecService)
        {
            _congViecServices = congViecServices;
            _vuViecService = vuViecService;
            _userGrpServices = userGrpServices;
            _authenServices = authenServices;
            _congViecVaVuViecService = congViecVaVuViecService;
        }
        #endregion

        #region -- Get Action --
        public ActionResult Index(string id, bool? chkTatCa)
        {
            #region Role user
            //if (GetUserVM() == null)
            //    return RedirectToAction("Index", "GC_Logon"); ;
            //permisson = GetPermission(_roleServices.GetRoleBy(sysFuncNo, GetUserVM().Email), Authorities.Access);
            //if (!permisson.Value)
            //    return View("AccessDenied");
            #endregion
            bool tatCa = chkTatCa ?? false;
            buildTree = new StringBuilder();
            userGroup = _userGrpServices.GetBy(id);
            if (!tatCa)
            {
                permissions = _authenServices.SystemFuncForTree(id);
                buildTree = TreeSystemFuncHelper.BuildTreeCongViecOfNhom(permissions);
            }
            else
            {
                var systemFuncs = _congViecServices.FindAll();
                buildTree = TreeSystemFuncHelper.BuildTreeSystemFunc(systemFuncs);
            }
            var authenVM = new AuthenticationVM()
            {
                CategoryTree = buildTree.ToString(),
                chkTatCa = tatCa,
                userGroups = userGroup
            };
            return View(authenVM);
        }
        #endregion

        /// <summary>
        /// Lấy vụ việc của công việc
        /// </summary>
        /// <param name="s">CategoryCode</param>
        /// <param name="g">GroupCode</param>
        /// <returns></returns>
        public ActionResult GetRoleSystemFunc(string c, string g)
        {
            IEnumerable<PermissionOnSystemFunc> lst = _authenServices.GetAllPermissionOnSystemFunc(c, g);
            return Json(lst);
        }

        /// <summary>
        /// Câp nhật quyền cho nhóm user
        /// </summary>
        /// <param name="sAndRVM">SystemFuncAndRoleVM</param>
        /// <returns></returns>
        public JsonResult UpdateRoles(CongViecVaVuViecVM congViecVaVuViecVM)
        {
            bool hasValue = false;
            var congViecVaVuViec = _congViecVaVuViecService.Get(congViecVaVuViecVM.c, congViecVaVuViecVM.u);
            var congViecVaVuViecs = new List<HT_CongViecVaVuViec>();
            congViecVaVuViecVM.fs.ToList().ForEach(item => {
                congViecVaVuViecs.Add(new HT_CongViecVaVuViec
                {
                    CategoryCode = congViecVaVuViecVM.c,
                    UserGroupCode = congViecVaVuViecVM.u,
                    FunctionCode = item
                });
            });
            if (congViecVaVuViec != null) //Update
                hasValue = string.IsNullOrEmpty(_congViecVaVuViecService.Update(congViecVaVuViecs)) ? true : false;
            else //Insert
                hasValue = string.IsNullOrEmpty(_congViecVaVuViecService.Insert(congViecVaVuViecs)) ? true : false;
            return Json(hasValue);
        }
    }
}

GCSOFT.MVC.Web/Areas/Administrator/Views/SysAuthentication/Index.cshtml
@model GCSOFT.MVC.Web.ViewModels.AuthenticationVM
@{
    ViewBag.Title = "CẤP QUYỀN TRUY CẬP";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript" src="@Url.Content("~/Scripts/cms/vendor/treeview/treeview.js")"></script>
<link type="text/css" href="@Url.Content("~/Scripts/cms/vendor/treeview/treeview.css")" rel="stylesheet" />
<div id="page_content_inner" class="hierarchical_slide">
    <div class="uk-grid uk-grid-medium" data-uk-grid-margin>
        <div class="uk-width-xLarge-3-10 uk-width-large-4-10">
            <div class="md-card">
                <div class="md-card-toolbar height45">
                    <h3 class="md-card-toolbar-heading-text">
                        CÔNG VIỆC NHÓM:&nbsp;<span class="uk-text-bold uk-text-primary">@Model.userGroups.Name.ToUpper()</span>
                    </h3>
                </div>
                <div class="md-card-content">
                    <div>
                        @Html.CheckBox("chkTatCa", Model.chkTatCa) Hiển thị tất cả công việc.
                    </div>
                    <div style="height: 90%; max-height: 400px; overflow: scroll; margin-left: 30px" id="divTreeCongViec">
                        @Html.Raw(Model.CategoryTree)
                    </div>
                </div>
            </div>
        </div>
        <div class="uk-width-xLarge-7-10  uk-width-large-6-10">
            <div class="md-card">
                <div class="md-card-toolbar height45">
                    <h3 class="md-card-toolbar-heading-text">
                        @ViewBag.Title: <span id="CategoryName" class="uk-text-bold uk-text-primary"></span>
                        @Html.Hidden("CategoryCode")
                    </h3>
                </div>
                <div class="md-card-content">
                    <table id="gridSource" class="uk-table uk-table-hover">
                        <thead>
                            <tr>
                                <th class="uk-width-1-10"><strong>STT</strong></th>
                                <th class="uk-width-2-10"><strong>Mã Vụ Việc</strong></th>
                                <th class="uk-width-2-10"><strong>Tên Vụ Việc</strong></th>
                                <th class="uk-text-right">
                                    <input type="checkbox" id="checkAll" name="checkAll" title="Click chọn tất cả." onclick="checkAllTbl('gridSource','checkAll')" />
                                </th>
                            </tr>
                        </thead>
                        <tbody id="tbody"></tbody>
                    </table>
                    <div class="uk-text-right">
                        <a href="@Url.Action("Index", "SysUserGroup", new { area = "Administrator" })" class="md-btn md-btn-flat"><i class="material-icons">&#xE31B;</i>&nbsp;Trở về</a>
                        <a id="btnUpdate" class="md-btn md-btn-primary" href="javascript:void(0)">Cập Nhật Quyền</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Section 1 -->
<script type="text/javascript">
    $(document).ready(function () {
        $("#navigation1").treeview({
            persist: "location",
            collapsed: true,
            unique: false
        });
        $("#chkTatCa").click(function () {
            location.href = '@Url.Action("Index/", "SysAuthentication", new { area = "Administrator" })' + '@Model.userGroups.Code' + '?chkTatCa=' + $(this).is(':checked');
        });
        //khi click vào công viêc tren tree
        $("#navigation1 a").click(function () {
            $.each($("#navigation1 a"), function () {
                $(this).css("color", "");
            });
            $(this).css("color", "red");
            $("#CategoryCode").val($(this).attr("alt"));
            $("#CategoryName").text($(this).html().toUpperCase());

            //xoa content table
            $.each($("#tbody tr"), function () {
                $(this).remove();
            });
            // Get vu viec
            $.post('@Url.Action("GetRoleSystemFunc", "SysAuthentication", new { area = "Administrator" })'
                    , { c: $(this).attr("alt"), g: '@Model.userGroups.Code' }
                    , function (data) {
                        if (data != null)
                            buildTableRole(data);
                    });

        }); //End load
        $('#btnUpdate').click(function () {
            if ($("#CategoryCode").val() == '') {
                $().toastmessage('showWarningToast', 'Bạn chưa chọn công việc cần cấp quyền !!!');
                return;
            }
            var roles = getRoles();
            $.post('@Url.Action("UpdateRoles", "SysAuthentication", new { area = "Administrator" })'
                , { c: $("#CategoryCode").val(), u: '@Model.userGroups.Code', f: getRoles }
                , function (data) {
                    if (data)
                        $().toastmessage('showSuccessToast', 'Đã cập nhật xong quyền<BR/>NHÓM:<br/>==> ' + '@Model.userGroups.Name.ToUpper()' + "<BR/>CÔNG VIỆC:<BR/>==> " + $("#CategoryName").text());
                    else
                        $().toastmessage('showErrorToast', "Cập nhật quyền bị lỗi !!!");
                }, "json");
        });
    });
    var buildTableRole = (function (data) {
        var stringBuilder = "";
        var count = 1;
        for (var i = 0; i < data.length; i++) {
            var dataIndex = data[i];
            stringBuilder += "<tr>";
            stringBuilder += "<td>" + count + "</td>";
            stringBuilder += "<td>" + dataIndex.FunctionNo + "</td>";
            stringBuilder += "<td>" + dataIndex.FunctionName + "</td>";
            if (dataIndex.Permission == true)
                stringBuilder += "<td class=\"uk-text-right\"><input type='checkbox' name='chk' value='" + dataIndex.FunctionNo + "' checked='checked' onclick=\"checkOneTable(this, 'gridSource','checkAll')\"/></td>";
            else
                stringBuilder += "<td class=\"uk-text-right\"><input type='checkbox' name='chk' value='" + dataIndex.FunctionNo + "' onclick=\"checkOneTable(this, 'gridSource','checkAll')\" /></td>";
            stringBuilder += "</tr>";
            ++count;
        }
        if (stringBuilder != "") {
            $("#tbody").html(stringBuilder);
        }
    });

    var getRoles = (function () {
        var str = "";
        //xoa content table
        $.each($("[name='chk']"), function () {
            if ($(this).is(":checked")) {
                str += $(this).val() + ",";
            }
        });
        return str.substring(0, str.length - 1);
    });
</script>