GCSOFT.MVC.AGENCY/Areas/Administrator/Controllers/SysUserController.cs
using AutoMapper;
using GCSOFT.MVC.Data.Common;
using GCSOFT.MVC.Model.AgencyModel;
using GCSOFT.MVC.Model.SystemModels;
using GCSOFT.MVC.Service.AgencyService.Interface;
using GCSOFT.MVC.Service.SystemService.Interface;
using GCSOFT.MVC.Web.Helper.ActionFilters;
using GCSOFT.MVC.Web.ViewModels.SystemViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GCSOFT.MVC.AGENCY.Areas.Administrator.Controllers
{
    [CompressResponseAttribute]
    public class SysUserController : BaseController
    {
        #region -- Properties --
        private readonly IVuViecService _vuViecService;
        private readonly IUserService _userService;
        private readonly IUserGroupService _userGroupService;
        private readonly IUserThuocNhomService _userThuocNhomService;
        private readonly IAgencyService _agenctyService;
        private string sysCategory = "U";
        private bool? permission = false;
        private UserCard userCard;
        private HT_Users user;
        private string hasValue;
        #endregion

        #region -- Contructor --
        public SysUserController
            (
                IVuViecService vuViecService
                , IUserService userService
                , IUserGroupService userGroupService
                , IUserThuocNhomService userThuocNhomService
                , IAgencyService agenctyService
            ) : base(vuViecService)
        {
            _vuViecService = vuViecService;
            _userService = userService;
            _userGroupService = userGroupService;
            _userThuocNhomService = userThuocNhomService;
            _agenctyService = agenctyService;
        }
        #endregion
        public ActionResult OpenPopupUser()
        {
            return PartialView("_PopupUser");
        }

        public ActionResult ChangePassword(int? id)
        {
            if (id == null)
                return PartialView("_ChangePassword", GetUser());
            var user = Mapper.Map<UserLoginVMs>(_userService.GetBy(id ?? 0));
            return PartialView("_ChangePassword", user);
        }

        //public ActionResult InfoAgency()
        //{
        //    var agency = _agenctyService.GetBy(GetUser().agencyInfo.Id);
        //    var model = Mapper.Map<AgencyList>(agency);
        //    return PartialView("_InfoAgency", model);
        //}

       

        public ActionResult ChangePasswordFirtLogin()
        {
            
            var user = Mapper.Map<UserLoginVMs>(_userService.GetBy(GetUser().ID));
            return View("ChangePasswordFirtLogin", user);
        }
        /// <summary>
        /// CheckIsUserUpdate
        /// </summary>
        /// <returns></returns>
        /// <history>
        ///     [Huỳnh Thử] Create [28/06/2021]
        /// </history>
        public JsonResult CheckIsUserUpdate()
        {
            var user = _userService.GetBy(GetUser().ID);
            DateTime date = DateTime.Now;
            var firstDayOfMonth = new DateTime(date.Year, date.Month, 1);
            var lastDayOfMonth = firstDayOfMonth.AddMonths(1).AddDays(-1);

            if (!user.LastDateUpdate.HasValue)
            {
                if (!user.IsUpdatePass)
                    return Json(new { status = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                if (!user.IsUpdatePass || DateTime.Compare(user.LastDateUpdate.Value, firstDayOfMonth) == -1)
                    return Json(new { status = true }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { status = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ChangePassword(UserLoginVMs userVM)
        {
            var user = _userService.GetBy(userVM.ID);
            user.Password = CryptorEngine.Encrypt(userVM.Password, true, "Hieu.Le-GC.Soft");
            user.IsUpdatePass = true;
            user.LastDateUpdate = DateTime.Now.Date;
            return Json(_userService.ChangePassword(user));
        }
        public JsonResult CandAdd(string u, string xu)
        {
            return Json(_userService.CandAdd(u, xu));
        }
    }
}

GCSOFT.MVC.AGENCY/Areas/Administrator/Views/SysUser/ChangePasswordFirtLogin.cshtml
@model GCSOFT.MVC.Web.ViewModels.SystemViewModels.UserLoginVMs
@{
    Layout = null;
}
<!doctype html>
<!--[if lte IE 9]> <html class="lte-ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="msapplication-tap-highlight" content="no" />

    @*<link rel="icon" type="image/png" href="@Url.Content("~/Content/cms/images/favicon-16x16.png")" sizes="16x16">*@

    <title>ĐĂNG NHẬP HỆ THỐNG</title>

    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500' rel='stylesheet' type='text/css'>

    @Styles.Render("~/login/css")
</head>
<body class="login_page">

    <div class="login_page_wrapper">
        <div class="md-card" id="login_card">
            <div class="md-card-content large-padding" id="login_form">
                <div class="login_heading">
                    <strong style="color: #2196f3;">Thay đổi mật khẩu lần đầu đăng nhập</strong>
                </div>
                @using (Html.BeginForm("ChangePassword", "SysUser", FormMethod.Post, new { @id = "frmChangePassword" }))
                {
                    <div class="uk-form-row">
                        @Html.HiddenFor(model => model.ID)
                        @Html.LabelFor(model => model.FullName)
                        @Html.TextBoxFor(model => model.FullName, new { @class = "md-input uk-form-width-large", @readonly = true })
                    </div>
                    <div class="uk-form-row">
                        @Html.LabelFor(model => model.Username)
                        @Html.TextBoxFor(model => model.Username, new { @class = "md-input uk-form-width-large", @readonly = true })
                    </div>
                    <div class="uk-form-row">
                        @Html.LabelFor(model => model.Password)
                        @Html.PasswordFor(model => model.Password, new { @class = "md-input uk-form-width-large validate[required]" })
                    </div>
                    <div class="uk-form-row">
                        @Html.LabelFor(model => model.RePassword)
                        @Html.PasswordFor(model => model.RePassword, new { @class = "md-input uk-form-width-large validate[required,equals[Password]]" })
                    </div>
                    <div class="uk-margin-medium-top">
                        <button id="btnChangePass" type="button" class="md-btn md-btn-primary md-btn-block md-btn-large">Thay Đổi Mật Khẩu</button>
                    </div>
                }
            </div>
        </div>
    </div>
    @Scripts.Render("~/cms/js")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnChangePass').click(function () {
                var objFrom = $('#frmChangePassword');
                var options = {
                    beforeSend: function () {
                        NProgress.start();
                        NProgress.set(0.4);
                    },
                    uploadProgress: function (event, position, total, percentComplete) {
                        NProgress.set(0.7);
                    },
                    success: function () {
                        NProgress.done();
                    },
                    complete: function (response) {
                        $(location).attr('href','@Url.Action("Index", "Login", new { area = "Administrator", msg = 2 })');
                    },
                    error: function () {
                        $().toastmessage('showErrorToast', "Lỗi, Vui lòng liên hệ với quản trị viên để được hổ trợ");
                    }
                }

                var flag = $.validation(objFrom);
                if (flag) {
                    objFrom.ajaxForm(options).submit();
                }
            });
        });
    </script>
</body>
</html>

GCSOFT.MVC.AGENCY/Areas/Administrator/Views/SysUser/Create.cshtml
@model GCSOFT.MVC.Web.ViewModels.SystemViewModels.UserCard
@{
    ViewBag.Title = "Thêm Mới Người Sử Dụng";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Create", "SysUser", FormMethod.Post, new { @id = "frm", @class = "uk-form-stacked" }))
{
    @Html.Partial("_CreateEdit")
}

GCSOFT.MVC.AGENCY/Areas/Administrator/Views/SysUser/Details.cshtml
@model GCSOFT.MVC.Web.ViewModels.SystemViewModels.UserCard
@{
    ViewBag.Title = "Chi Tiết Người Sử Dụng";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
    int stt = 0;
}
@using (Html.BeginForm())
{
<div id="page_content_inner" class="hierarchical_slide">
	<div class="md-card">
		<div class="md-card-toolbar">
			<h3 class="md-card-toolbar-heading-text">
				<i class="material-icons">&#xE894;</i>&nbsp;&nbsp;@ViewBag.Title
			</h3>
            <div class="md-card-toolbar-actions">
                <i class="md-icon material-icons md-card-toggle">&#xE316;</i>
            </div>
		</div>
		<div class="md-card-content gc-padding-top-8">
			<div class="uk-grid gc-margin-top-0px">
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">@Model.Username</span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.userGroupCodes, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">
                            @foreach (var item in Model.userGroups)
                            {
                                if (stt != 0)
                                {
                                    @:, <a href="@Url.Action("Details/", "SysUserGroup", new { area = "administrator" })@item.Code">@item.Name</a>
                                }
                                else
                                {
                                    <a href="@Url.Action("Details/", "SysUserGroup", new { area = "administrator" })@item.Code">@item.Name</a>
                                }
                                stt += 1;
                            }
                        </span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
			</div>
			<div class="uk-grid gc-margin-top-0px uk-hidden-small">
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
			</div>
			<div class="uk-grid gc-margin-top-0px">
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">@Model.FirstName</span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">@Model.LastName</span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
			</div>
			<div class="uk-grid gc-margin-top-0px uk-hidden-small">
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
			</div>
			<div class="uk-grid gc-margin-top-0px">
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">@Model.Email</span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">@Model.Phone</span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
			</div>
			<div class="uk-grid gc-margin-top-0px uk-hidden-small">
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
			</div>
			<div class="uk-grid gc-margin-top-0px">
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">@Model.Address</span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.Blocked, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">
                            @Html.CheckBoxFor(model => model.Blocked, new Dictionary<string, Object> { { "data-md-icheck", "" }, { "disabled", true } })
                        </span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
			</div>
			<div class="uk-grid gc-margin-top-0px uk-hidden-small">
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
			</div>
			<div class="uk-grid gc-margin-top-0px">
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">@Model.Position</span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
				<div class="uk-width-medium-1-2">
					<div class="uk-width-medium-1-1">
						@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "gc-text-muted uk-text-small" })
					</div>
					<div class="uk-width-medium-1-1 gc-margin-top-2px">
						<span class="uk-text-middle">@Model.Description</span>
					</div>
					<hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
				</div>
			</div>
			<div class="uk-grid gc-margin-top-0px uk-hidden-small">
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
				<div class="uk-width-medium-1-2">
					<hr class="gc-grid-divider">
				</div>
			</div>
		</div>
	</div>
</div>
<div class="md-fab-wrapper">
    <a id="btnReturn" href="@Url.Action("Index", "SysUser", new { area = "administrator" })" class="md-fab md-fab-small md-fab-accent" title="Quay lại" data-uk-tooltip="{pos:'top'}"><i class="material-icons">&#xE31B;</i></a>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        gcHotkey._return();
    });
</script>
}

GCSOFT.MVC.AGENCY/Areas/Administrator/Views/SysUser/Edit.cshtml
@model GCSOFT.MVC.Web.ViewModels.SystemViewModels.UserCard
@{
    ViewBag.Title = "Cập Nhật Người Sử Dụng";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Edit", "SysUser", FormMethod.Post, new { @id = "frm", @class = "uk-form-stacked" }))
{
    @Html.Partial("_CreateEdit")
}

GCSOFT.MVC.AGENCY/Areas/Administrator/Views/SysUser/Index.cshtml
@model IEnumerable<GCSOFT.MVC.Web.ViewModels.SystemViewModels.UserList>

@{
    ViewBag.Title = "Người Sử Dụng";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}
<div id="page_content_inner" class="hierarchical_slide">
    <div class="md-card">
        <div class="md-card-toolbar">
            <h3 class="md-card-toolbar-heading-text">
                <i class="material-icons">&#xE894;</i>&nbsp;&nbsp;@ViewBag.Title
            </h3>
        </div>
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table id="jqGrid"></table>
                <div id="jqGridPager"></div>
            </div>
        </div>
    </div>
</div>
<div class="md-fab-wrapper">
    <div class="md-fab md-fab-accent md-fab-sheet md-fab-small">
        <i class="material-icons">&#xE30F;</i>
        <div class="md-fab-sheet-actions">
            <a name="btnDel" href="javascript:void(0)" class="md-color-white">
                <i class="material-icons md-color-white">&#xE872;</i> <span class="gc-text-decoration uk-text-warning">X</span>óa
            </a>
            <a name="btnEdit" href="javascript:void(0)" class="md-color-white">
                <i class="material-icons md-color-white">&#xE254;</i> <span class="gc-text-decoration uk-text-warning">S</span>ửa
            </a>
            <a name="btnAdd" href="@Url.Action("Create", "SysUser", new { area = "administrator" })" class="md-color-white">
                <i class="material-icons md-color-white">&#xE148;</i> <span class="gc-text-decoration uk-text-warning">T</span>hêm
            </a>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            LoadGrid('@Url.Action("LoadData", "SysUser", new { area = "administrator" })');
            CallHotKey();
            $('[name="btnEdit"]').click(function () {
                JqEdit('@Url.Action("Edit", "SysUser", new { area = "administrator" })', 'jqGrid')
            });
            $('[name="btnDel"]').click(function () {
                JqDel('@Url.Action("Deletes", "SysUser", new { area = "administrator" })', $('#jqGrid'));
            });
        });

        function LoadGrid(url) {
            $("#jqGrid").jqGrid({
                url: url,
                mtype: "get",
                datatype: "json",
                colNames: [
                                '@Html.DisplayNameFor(model => model.ID)'
                                , '@Html.DisplayNameFor(model => model.Username).ToString().Replace("(*)","")'
                                , '@Html.DisplayNameFor(model => model.FullName)'
								, '@Html.DisplayNameFor(model => model.Email).ToString().Replace("(*)", "")'
								, '@Html.DisplayNameFor(model => model.Phone).ToString().Replace("(*)", "")'
                                , '@Html.DisplayNameFor(model => model.Blocked)'
                                , 'Mật khẩu'
				],
                colModel: [
                                { name: 'ID', index: 'ID', hidden: true }
								, { name: 'Username', index: 'Username', formatter: NoFormatter }
                                , { name: 'FullName', index: 'FullName' }
                                , { name: 'Email', index: 'Email' }
                                , { name: 'Phone', index: 'Phone' }
                                , { name: 'BlockedStr', index: 'BlockedStr', width: 30, align: 'center' }
                                , { name: 'ID', index: 'ID', width: 30, align: 'center', formatter: ChangePassFormatter }

				],
                rowNum: 20,
                rowList: [20, 40, 60, 80, 100],
                pager: '#jqGridPager',
                sortname: 'ID',
                viewrecords: true,
                autowidth: true,
                height: "100%",
                sortorder: "asc",
                multiselect: true,
                rownumbers: true,
                //viewsortcols: [true, 'vertical', true],
                loadComplete: function () {
                    jqGrid_resize('jqGrid');
                    gridSearch('jqGrid', 'search-button');
                    GetDetails();
                    OpenPopupChangePass();
                },
                jsonReader: {
                    root: "Rows",
                    page: "jqGridPager",
                    total: "Total",
                    records: "Records",
                    repeatitems: false,
                    id: "ID"
                }
            });
            $("#jqGrid").jqGrid('navGrid', '#jqGridPager',
                    { edit: false, add: false, del: false }, {}, {}, {},
                    {
                        multipleSearch: true,
                        closeOnEscape: true,
                        closeAfterSearch: true,
                        showQuery: true,
                        searchOnEnter: true,
                        sopt: ['cn', 'eq', 'ne', 'lt', 'le', 'gt', 'ge']
                    }
                );
        }

        function NoFormatter(cellvalue, options, rowObject) {
            return '<strong><a href="@Url.Action("Details/", "SysUser", new { area = "administrator" })' + rowObject.ID + '" title="Xem chi tiết" name="Details" data-uk-tooltip="{pos:\'top\'}">' + cellvalue + '</a></strong>';
        }

        function ChangePassFormatter(cellvalue, options, rowObject) {
            return '<a name="ChangePassword" href="javascript:void(0);" accesskey="@Url.Action("ChangePassword/", "SysUser", new { area = "administrator" })' + rowObject.ID + '" title="Đổi mật khẩu" data-uk-tooltip="{pos:\'top\'}"><i class="md-icon material-icons uk-text-primary">&#xE86A;</i></a>';
        }

		function GetDetails() {
            $('[name="Details"]').click(function () {
                var idx = $('[name="Details"]').index($(this));
                $(location).attr('href', $('[name="Details"]:eq(' + idx + ')').attr('href'));
            });
            gcHotkey._view();
        }

        function OpenPopupChangePass() {
            $('[name="ChangePassword"]').click(function () {
                var idx = $('[name="ChangePassword"]').index($(this));
                OpenDialog($('[name="ChangePassword"]:eq(' + idx + ')'), $('[name="ChangePassword"]:eq(' + idx + ')').attr('accesskey'), '');
            });
        }

        function CallHotKey() {
            gcHotkey._add();
            gcHotkey._edit();
            gcHotkey._del();
        }
    </script>
}

GCSOFT.MVC.AGENCY/Areas/Administrator/Views/SysUser/_ChangePassword.cshtml
@model GCSOFT.MVC.Web.ViewModels.SystemViewModels.UserLoginVMs
@using (Html.BeginForm("ChangePassword", "SysUser", FormMethod.Post, new { @id = "frmChangePassword", @class = "uk-form-stacked" }))
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/cms/js/altair_admin_common.js")"></script>
    <div class="md-card md-card-popup">
        <div class="md-card-toolbar md-card-toolbar-popup">
            <h3 class="md-card-toolbar-heading-text">
                Đổi Mật Khẩu
                @Html.HiddenFor(model => model.ID)
            </h3>
        </div>
        <div class="md-card-content md-card-content-popup">
            <!-- Row 1 -->
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1">
                    @Html.LabelFor(model => model.FullName)
                    @Html.TextBoxFor(model => model.FullName, new { @class = "md-input uk-form-width-large", @readonly = true })
                </div>
            </div>
            <!-- Row 2 -->
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1">
                    @Html.LabelFor(model => model.Username)
                    @Html.TextBoxFor(model => model.Username, new { @class = "md-input uk-form-width-large", @readonly = true })
                </div>
            </div>
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1">
                    @Html.LabelFor(model => model.Password)
                    @Html.PasswordFor(model => model.Password, new { @class = "md-input uk-form-width-large validate[required]" })
                </div>
            </div>
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1">
                    @Html.LabelFor(model => model.RePassword)
                    @Html.PasswordFor(model => model.RePassword, new { @class = "md-input uk-form-width-large validate[required,equals[Password]]" })
                </div>
            </div>
            <div class="uk-grid uk-margin-medium-top">
                <div class="uk-width-1-1 uk-text-right">
                    <button id="btnChangePass" type="button" class="md-btn md-btn-primary">Thay Đổi Mật Khẩu</button>
                </div>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $('#btnChangePass').click(function () {
            var objFrom = $('#frmChangePassword');
            var options = {
                beforeSend: function () {
                    NProgress.start();
                    NProgress.set(0.4);
                },
                uploadProgress: function (event, position, total, percentComplete) {
                    NProgress.set(0.7);
                },
                success: function () {
                    NProgress.done();
                },
                complete: function (response) {
                    $().toastmessage('showToast', {
                        text: "Cập nhật mật khẩu thành công",
                        sticky: false,
                        position: 'top-center',
                        type: 'success'
                    });
                    $.fancybox.close();
                },
                error: function () {
                    $().toastmessage('showErrorToast', "Lỗi, Vui lòng liên hệ với quản trị viên để được hổ trợ");
                }
            }

            var flag = $.validation(objFrom);
            if (flag) {
                objFrom.ajaxForm(options).submit();
            }
        });
    });
</script>

GCSOFT.MVC.AGENCY/Areas/Administrator/Views/SysUser/_InfoAgency.cshtml
@model GCSOFT.MVC.AGENCY.Areas.Agency.Data.AgencyList
    <script type="text/javascript" src="@Url.Content("~/Scripts/cms/js/altair_admin_common.js")"></script>
    <div class="md-card md-card-popup">
        <div class="md-card-toolbar md-card-toolbar-popup">
            <h3 class="md-card-toolbar-heading-text">
                Thông Tin Đối Tác
            </h3>
        </div>
        <div class="md-card-content md-card-content-popup">
            <!-- Row 1 -->
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1">
                    @Html.LabelFor(model => model.FullName)
                    @Html.TextBoxFor(model => model.FullName, new { @class = "md-input uk-form-width-large", @readonly = true })
                </div>
            </div>
            <!-- Row 2 -->
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1">
                    @Html.LabelFor(model => model.Phone)
                    @Html.TextBoxFor(model => model.Phone, new { @class = "md-input uk-form-width-large", @readonly = true })
                </div>
            </div>
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1">
                    @Html.LabelFor(model => model.Email)
                    @Html.TextBoxFor(model => model.Email, new { @class = "md-input uk-form-width-large", @readonly = true })
                </div>
            </div>
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1">
                    @Html.LabelFor(model => model.AgencyNo)
                    @Html.TextBoxFor(model => model.AgencyNo, new { @class = "md-input uk-form-width-large" })
                    <span class="uk-input-group-addon"><a class="md-btn md-btn-flat md-btn-flat-primary md-btn-wave waves-effect waves-button" href="javascript:void(0);" id="btnReSendAPIKey">Lấy API Key</a></span>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
    $(document).ready(function () {
        $('#btnReSendAPIKey').click(function () {
            NProgress.start();
           $('#btnReSendAPIKey').addClass("disabled").text('Đang tạo ....');
            $.post('@Url.Action("ResendAPIKey", "SysUser", new { area = "Administrator" })', { id: $('#Id').val() }, function (data) {
                $().toastmessage('showToast', {
                    text: 'Lấy API key mới thành công!',
                    sticky: false,
                    position: 'top-center',
                    type: 'success'
                });
                $('#AgencyNo').text(data).val(data);
                $('#btnReSendAPIKey').removeClass("disabled").text('Lấy API Key');
                NProgress.done();
            });
        });
    });
    </script>