GCSOFT.MVC.STNHD/Models/NamPhutViewModels/NopBai.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GCSOFT.MVC.STNHD.Models.NamPhutViewModels
{
    public class NopBai
    {
        public int Id { get; set; }
        public string userName { get; set; }
        public string SBD { get; set; }
        public string FullName { get; set; }
        public string CodeDethi { get; set; }
        public int IdContestants { get; set; }
        public string LinkFacebok { get; set; }
        public int? LuotView { get; set; }
        public int? LuotInteract { get; set; }
        public int? LuotShare { get; set; }
        public int? LuotComment { get; set; }
        public int IdTrongTaiVong1 { get; set; }
        public int IdTrongTaiChuyenMon1 { get; set; }
        public int IdTrongTaiChuyenMon2 { get; set; }
        public DateTime DateInput { get; set; }
        public int TieuChi1 { get; set; }
        public int TieuChi2 { get; set; }
        public int TieuChi3 { get; set; }
        public int TieuChi4 { get; set; }
        public int TieuChi5 { get; set; }
        public int ChuyenMon1_TrinhBay1 { get; set; }
        public int ChuyenMon1_TrinhBay2 { get; set; }
        public int ChuyenMon1_TrinhBay3 { get; set; }
        public int ChuyenMon1_NoiDung { get; set; }
        public int ChuyenMon1_Mindmap { get; set; }
        public int ChuyenMon2_TrinhBay1 { get; set; }
        public int ChuyenMon2_TrinhBay2 { get; set; }
        public int ChuyenMon2_TrinhBay3 { get; set; }
        public int ChuyenMon2_NoiDung { get; set; }
        public int ChuyenMon2_Mindmap { get; set; }
        public int TongDiem { get; set; }
        public int Point { get; set; }
        public string Vong1StatusCode { get; set; }
        public string Vong1StatusName { get; set; }
        public string StatusCode { get; set; }
        public string StatusName { get; set; }
        public string ChuyenMon1_StatusCode { get; set; }
        public string ChuyenMon1_StatusName { get; set; }
        public string ChuyenMon2_StatusCode { get; set; }
        public string ChuyenMon2_StatusName { get; set; }
        public bool IsChuyenMon { get; set; }
        public string UserTrongTaiVong1 { get; set; }
        public string UserTrongTaiChuyenMon1 { get; set; }
        public string UserTrongTaiChuyenMon2 { get; set; }
        public int TongDiemVong1 { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public string FullNameTrongTaiVong1 { get; set; }
        public string FullNameTrongTaiChuyenMon1 { get; set; }
        public string FullNameTrongTaiChuyenMon2 { get; set; }
        public string NhaDtXuatSacCode { get; set; }
        public string NhaDtXuatSacName { get; set; }
        public string NhaDTTruyenCamHungCode { get; set; }
        public string NhaDTTruyenCamHungName { get; set; }

        public IEnumerable<SelectListItem> StatusList { get; set; }
        public IEnumerable<SelectListItem> ChuyenMon1StatusList { get; set; }
        public IEnumerable<SelectListItem> ChuyenMon2StatusList { get; set; }
        public IEnumerable<SelectListItem> TrongTaiVong1List { get; set; }
        public IEnumerable<SelectListItem> ChuyenMon1List { get; set; }
        public IEnumerable<SelectListItem> ChuyenMon2List { get; set; }
        public Contestants userInfo { get; set; }
        public NopBai()
        {
            userInfo = new Contestants();
        }
    }
}

GCSOFT.MVC.STNHD/Controllers/NamPhutThuocBaiController.cs
using AutoMapper;
using GCSOFT.MVC.Data.Common;
using GCSOFT.MVC.Model.MasterData;
using GCSOFT.MVC.Model.NamPhutThuocBai;
using GCSOFT.MVC.Service.MasterDataService.Interface;
using GCSOFT.MVC.Service.NamPhutThuocBaiService.Interface;
using GCSOFT.MVC.Service.STNHDService.Interface;
using GCSOFT.MVC.Service.StoreProcedure.Interface;
using GCSOFT.MVC.Service.SystemService.Interface;
using GCSOFT.MVC.Service.Transaction.Interface;
using GCSOFT.MVC.STNHD.Helper;
using GCSOFT.MVC.STNHD.Models;
using GCSOFT.MVC.STNHD.Models.NamPhutViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GCSOFT.MVC.STNHD.Controllers
{
    public class NamPhutThuocBaiController : BaseController
    {
        private readonly IShareInfoService _shareInfoService;
        private readonly IClassService _classService;
        private readonly IProvinceService _provinceService;
        private readonly IDistrictService _districtService;
        private readonly IUserInfoService _userInfoService;
        private readonly ISMSService _smsService;
        private readonly IVuViecService _vuViecRepo;
        private readonly IContestantsService _contestantService;
        private readonly IStoreProcedureService _storeProService;
        private readonly IDeThiService _deThiService;
        private readonly INopBaiService _nopBaiService;
        private readonly IGiftService _giftService;
        private readonly IPointEntryService _pointEntryService;
        private readonly ITransactionGiftService _transGiftService;
        private string hasValue;
        public NamPhutThuocBaiController
            (
                IShareInfoService shareInfoService
                , IClassService classService
                , IProvinceService provinceService
                , IDistrictService districtService
                , IUserInfoService userInfoService
                , ISMSService smsService
                , IVuViecService vuViecRepo
                , IContestantsService contestantService
                , IStoreProcedureService storeProService
                , IDeThiService deThiService
                , INopBaiService nopBaiService
                , IGiftService giftService
                , IPointEntryService pointEntryService
                , ITransactionGiftService transGiftService
            ) : base(shareInfoService)
        {
            _shareInfoService = shareInfoService;
            _classService = classService;
            _provinceService = provinceService;
            _districtService = districtService;
            _userInfoService = userInfoService;
            _smsService = smsService;
            _vuViecRepo = vuViecRepo;
            _contestantService = contestantService;
            _storeProService = storeProService;
            _deThiService = deThiService;
            _nopBaiService = nopBaiService;
            _giftService = giftService;
            _pointEntryService = pointEntryService;
            _transGiftService = transGiftService;
        }
        // GET: NamPhuThuocBai
        public ActionResult Index()
        {
            InitLanguage();
            var userName = "";
            if (System.Web.HttpContext.Current.Request.Cookies["userNamPhut"] != null)
                userName = System.Web.HttpContext.Current.Request.Cookies["userNamPhut"].Value;
            var thiSinhInfo = new Contestants();
            var tongDiem = 0;
            if (!string.IsNullOrEmpty(userName))
            {
                thiSinhInfo = Mapper.Map<Contestants>(_contestantService.GetByUserName(userName)) ?? new Contestants();
                tongDiem = _pointEntryService.TotalPoint(userName); ;
            }
            ViewBag.BaiThi = _storeProService.SP_BaiThi(userName);
            ViewBag.userName = userName;
            ViewBag.ThiSinh = thiSinhInfo;
            ViewBag.tongDiem = tongDiem;
            return View();
        }
        public ActionResult BaiDuThi()
        {
            InitLanguage();
            if (System.Web.HttpContext.Current.Request.Cookies["userNamPhut"] == null)
                return RedirectToAction("DangNhapCuocThi");
            ViewBag.BaiThi = _storeProService.SP_BaiThi(GetUserName());
            return View();
        }
        [HttpGet]
        public ActionResult NopBai(string c)
        {
            InitLanguage();
            if (System.Web.HttpContext.Current.Request.Cookies["userNamPhut"] == null)
                return RedirectToAction("DangNhapCuocThi");
            var deThi = Mapper.Map<DeThi>(_deThiService.GetBy(c));
            ViewBag.DeThi = deThi;
            var userInfo = Mapper.Map<Contestants>(_contestantService.GetByUserName(GetUserName()));
            var nopBai = new NopBai()
            {
                userInfo = userInfo,
                Id = 0,
                CodeDethi = deThi.Code,
                IdContestants = userInfo.Id,
                userName = userInfo.Username,
                SBD = userInfo.IdentificationNumber,
                FullName = userInfo.ChildName,
                ClassId = userInfo.GradeId,
                ClassName = userInfo.GradeName
            };
            return View(nopBai);
        }
        [HttpPost]
        public ActionResult NopBai(NopBai nopBai)
        {
            InitLanguage();
            var schoolClass = Mapper.Map<ClassList>(_classService.Get(nopBai.ClassId));
            nopBai.ClassName = schoolClass.Name;
            nopBai.DateInput = DateTime.Now;
            hasValue = _nopBaiService.Insert(Mapper.Map<TB_NopBai>(nopBai));
            hasValue = _vuViecRepo.Commit();
            var url = Url.Action("BaiDuThi", new { msg = 2 });
            return Json(new { url = url }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult CapNhatBaiNop(string c, int id)
        {
            InitLanguage();
            if (System.Web.HttpContext.Current.Request.Cookies["userNamPhut"] == null)
                return RedirectToAction("DangNhapCuocThi");
            var deThi = Mapper.Map<DeThi>(_deThiService.GetBy(c));
            ViewBag.DeThi = deThi;
            var userInfo = Mapper.Map<Contestants>(_contestantService.GetByUserName(GetUserName()));
            var nopBai = Mapper.Map<NopBai>(_nopBaiService.Get(id));
            nopBai.userInfo = userInfo;
            return View(nopBai);
        }
        [HttpGet]
        public ActionResult CapNhatLuotView(string c, int id)
        {
            InitLanguage();
            if (System.Web.HttpContext.Current.Request.Cookies["userNamPhut"] == null)
                return RedirectToAction("DangNhapCuocThi");
            var deThi = Mapper.Map<DeThi>(_deThiService.GetBy(c));
            ViewBag.DeThi = deThi;
            var userInfo = Mapper.Map<Contestants>(_contestantService.GetByUserName(GetUserName()));
            var nopBai = Mapper.Map<NopBai>(_nopBaiService.Get(id));
            nopBai.userInfo = userInfo;
            return View(nopBai);
        }
        [HttpPost]
        public ActionResult CapNhatLuotView(NopBai nopBai)
        {
            InitLanguage();
            var _nopBai = _nopBaiService.Get(nopBai.Id);
            _nopBai.LuotView = nopBai.LuotView ?? 0;
            _nopBai.LuotInteract = nopBai.LuotInteract ?? 0;
            _nopBai.LuotShare = nopBai.LuotShare ?? 0;
            _nopBai.LuotComment = nopBai.LuotComment ?? 0;
            hasValue = _nopBaiService.Update(_nopBai);
            hasValue = _vuViecRepo.Commit();
            var url = Url.Action("BaiDuThi", new { msg = 2 });
            return Json(new { url = url }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult CapNhatBaiNop(NopBai nopBai)
        {
            InitLanguage();
            var _nopBai = _nopBaiService.Get(nopBai.Id);
            _nopBai.LinkFacebok = nopBai.LinkFacebok;
            _nopBai.LuotView = nopBai.LuotView ?? 0;
            _nopBai.LuotInteract = nopBai.LuotInteract ?? 0;
            _nopBai.LuotShare = nopBai.LuotShare ?? 0;
            _nopBai.LuotComment = nopBai.LuotComment ?? 0;
            hasValue = _nopBaiService.Update(_nopBai);
            hasValue = _vuViecRepo.Commit();
            var url = Url.Action("BaiDuThi", new { msg = 2 });
            return Json(new { url = url }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DangKy(string id)
        {
            InitLanguage();
            var contestants = new Contestants()
            {
                ClassList = Mapper.Map<IEnumerable<ClassList>>(_classService.FindAll(ClassType.Class, "SHOW")).ToList().ToSelectListItems(0),
                CityList = Mapper.Map<IEnumerable<ProvinceViewModel>>(_provinceService.FindAll()).ToSelectListItems(0),
                DistrictList = Mapper.Map<IEnumerable<DistrictViewModel>>(_districtService.FindAll(0)).ToSelectListItems(0)
            };
            if (!string.IsNullOrEmpty(id))
            {
                var userInfo = Mapper.Map<UserInfoViewModel>(_userInfoService.GetBy(int.Parse(id)));
                contestants.IsAccountSTNHD = true;
                contestants.Username = userInfo.userName;
                contestants.Password = userInfo.Password;
                contestants.ChildName = userInfo.fullName;
                contestants.Email = userInfo.Email;
                contestants.Phone = userInfo.Phone;
                contestants.Address = userInfo.Address;
            }
            return View(contestants);
        }
        public ActionResult DangNhapCuocThi()
        {
            InitLanguage();
            if (System.Web.HttpContext.Current.Request.Cookies["userNamPhut"] != null)
                System.Web.HttpContext.Current.Request.Cookies["userNamPhut"].Expires = DateTime.Now.AddDays(-1);
            return View();
        }
        public ActionResult QuenTenDangNhapVaMatKhau()
        {
            InitLanguage();
            

GCSOFT.MVC.STNHD/Views/NamPhutThuocBai/BaiDuThi.cshtml
@model GCSOFT.MVC.STNHD.Models.NamPhutViewModels.NopBai
@using GCSOFT.MVC.Model.StoreProcedue
@{
    ViewBag.Title = "Bài Dự Thi";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var baiThis = (IEnumerable<SPBaiThi>)ViewBag.BaiThi;
}
<div class="container">
    <div class="row" style="padding-top: 20px;">
        <div class="col-lg-12 col-md-12 col-sm-12 text-center">
            @Html.Partial("_MenuThiSinh")
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="text-center"><h3 class="h-title" style="margin-bottom: 29px; color: #337ab7; margin-top: 35px;">Danh Sách Đề Thi</h3></div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            @foreach (var item in baiThis)
            {
                <div class="post">
                    <div class="post-top">
                        <div class="media">
                            <div class="media-body">
                                <h4 class="media-heading" style="color: #FF660F;">@item.Title</h4>
                                <p>@item.NgayBatDauStr - @item.NgayKetThucStr</p>
                            </div>
                        </div>
                        <p class="txt">
                            @Html.Raw(item.Description)
                        </p>

                        <div class="text-left post-btn">
                            @if (item.StatusCode == 1)
                            {

                                <a href="@Url.Action("NopBai", "NamPhutThuocBai", new { c = item.Code })">@item.StatusName</a>
                            }
                            else if (item.StatusCode == 2)
                            {
                                <a href="@Url.Action("CapNhatBaiNop", "NamPhutThuocBai", new { c = item.Code, id = item.Id })">@item.StatusName</a>
                            }
                            else
                            {
                                <a href="javascript:void(0);">@item.StatusName</a>
                            }
                            @if (item.Code.StartsWith("TUAN2"))
                            {
                                <a href="@Url.Action("CapNhatLuotView", "NamPhutThuocBai", new { c = item.Code, id = item.Id })">Cập nhật lượt View</a>
                            }
                        </div>
                        @if (!string.IsNullOrEmpty(item.Remark1))
                        {
                            <p class="txt">
                                <strong>Ghi chú Trọng Tài</strong>
                                @Html.Raw(item.Remark1)
                            </p>
                        }
                        @if (!string.IsNullOrEmpty(item.Remark2))
                        {
                            <p class="txt">
                                <strong>Ghi chú trọng tài video</strong>
                                @Html.Raw(item.Remark2)
                            </p>
                        }
                        @if (!string.IsNullOrEmpty(item.Remark3))
                        {
                            <p class="txt">
                                <strong>Ghi chú trọng tài mindmap</strong>
                                @Html.Raw(item.Remark3)
                            </p>
                        }
                    </div>
                    <div class="clear-both"></div>
                </div>
                <div class="clear-both"></div>
            }
        </div>
    </div>
</div>
@section scripts{
    <link href="@Url.Content("~/Scripts/ValidationEngine/validationEngine.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/ValidationEngine/validationEngine.js")"></script>
    <script src="@Url.Content("~/Scripts/ValidationEngine/validationEngine-vi.js")"></script>
    <link href="@Url.Content("~/Scripts/toast/toast.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/toast/toast.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            if ($.urlParam('msg') == '2') {
                $.toast({
                    heading: 'Xin Chúc Mừng',
                    text: 'Bài dự thi của em đã được gửi đến giáo viên Tâm Trí Lực, kết quả sẽ được trả về qua Email và SMS trong thời gian sớm nhất',
                    showHideTransition: 'slide',
                    icon: 'info',
                    position: 'top-center',
                    hideAfter: 20000
                });
            }

        });
        $.urlParam = function (name) {
            var results = new RegExp('[\\?&]' + name + '=([^&#]*)').exec(window.location.href);
            if (results == null) {
                return '';
            } else {
                return results[1] || 0;
            }
        }
    </script>
}

GCSOFT.MVC.STNHD/Views/NamPhutThuocBai/CapNhatBaiNop.cshtml
@model GCSOFT.MVC.STNHD.Models.NamPhutViewModels.NopBai
@using GCSOFT.MVC.STNHD.Models.NamPhutViewModels
@{
    ViewBag.Title = "Nộp Bài Thi";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //var userInfo = (Contestants)ViewBag.userInfo;
    var deThi = (DeThi)ViewBag.DeThi;
}
}
<div class="container">
    <div class="row" style="margin-bottom: 30px;">
        <div class="col-lg-12 col-md-12 col-sm-12 text-center">
            @Html.Partial("_MenuThiSinh")
        </div>
    </div>
    <div class="row">
        <div class="col-lg-offset-2 col-md-offset-2 col-xs-12 col-sm-12 col-md-8 col-lg-8 mt-90">
            <div class="modify-w-form contact post">
                <h3 style="text-align: center;">
                    NỘP BÀI DỰ THI
                </h3>
                <h4>@deThi.Title</h4>
                <p>
                    @Html.Raw(deThi.Description)
                </p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div id="divSuccessRegistration" class="modify-w-form contact" style="text-align: center; display: none;">
                <h3 style="text-align: center; margin-top: 25px;">Xin Chúc Mừng</h3>
                <p id="msgSuccessRegistration"></p>
            </div>
            <div class="modify-w-form" id="divRegistration">
                @using (Html.BeginForm("CapNhatBaiNop", "NamPhutThuocBai", FormMethod.Post, new { @id = "frmNopBai", @autocomplete = "off", @class = "form-horizontal" }))
                {
                    <div class="support-course">
                        <p>Thông tin thí sinh</p>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Số báo danh</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(model => model.userInfo.IdentificationNumber, new { @placeholder = "Số Báo Danh", @class = "form-control", @readonly = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Họ và Tên</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(model => model.userInfo.ChildName, new { @placeholder = "Họ tên con", @class = "form-control", @readonly = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Trường</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(model => model.userInfo.SchoolName, new { @placeholder = "Trường", @class = "form-control", @readonly = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Lớp</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(model => model.userInfo.GradeName, new { @placeholder = "Lớp", @class = "form-control", @readonly = true })
                            </div>
                        </div>
                    </div>
                    <div class="support-course">
                        <p>Thông tin bài nộp</p>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Link facebook Bài Thi</label>
                            <div class="col-sm-9">
                                @Html.HiddenFor(model => model.Id)
                                @Html.HiddenFor(model => model.CodeDethi)
                                @Html.HiddenFor(model => model.IdContestants)
                                @Html.HiddenFor(model => model.userName)
                                @Html.HiddenFor(model => model.SBD)
                                @Html.HiddenFor(model => model.FullName)
                                @Html.HiddenFor(model => model.ClassId)
                                @Html.HiddenFor(model => model.ClassName)

                                @Html.TextBoxFor(model => model.LinkFacebok, new { @placeholder = "Link facebook nộp bài (*)", @class = "form-control validate[required]" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Số Lượt view hiện có</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(model => model.LuotView, new { @placeholder = "Nhập số lượt view trên facebook (*)", @class = "form-control validate[required]" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Số Lượt tương tác hiện có (Like,Tim,HaHa...)</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(model => model.LuotInteract, new { @placeholder = "Nhập số lượt tương tác trên facebook (*)", @class = "form-control validate[required]" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Số Lượt chia sẻ hiện có</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(model => model.LuotShare, new { @placeholder = "Nhập số lượt chia sẻ trên facebook (*)", @class = "form-control validate[required]" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Số Lượt bình luận hiện có</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(model => model.LuotComment, new { @placeholder = "Nhập số lượt bình luận trên facebook (*)", @class = "form-control validate[required]" })
                            </div>
                        </div>
                    </div>
                    <div class="text-center"><button type="button" id="btnNopBai" class="btn btn-primary">Nộp Bài Dự Thi</button></div>
                }
            </div>

        </div>
    </div>
</div>
@section scripts{
    <link href="@Url.Content("~/Scripts/ValidationEngine/validationEngine.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/ValidationEngine/validationEngine.js")"></script>
    <script src="@Url.Content("~/Scripts/ValidationEngine/validationEngine-vi.js")"></script>
    <link href="@Url.Content("~/Scripts/toast/toast.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/toast/toast.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnNopBai').click(function () {
                var objFrom = $('#frmNopBai');
                var flag = objFrom.validationEngine('validate');
                if (flag) {
                    NProgress.start();
                    objFrom.ajaxSubmit(function (data) {
                        window.location.href = data.url;
                    });
                }
            });
        });
    </script>
}

GCSOFT.MVC.STNHD/Views/NamPhutThuocBai/DangKyThanhCong.cshtml
@model GCSOFT.MVC.STNHD.Models.NamPhutViewModels.Contestants
@{
    ViewBag.Title = "Đăng Ký Thành Công - Cuộc Thi 5 Phút Thuộc Bài";
}
<div class="container">
    <div class="row">
        <div class="col-lg-offset-2 col-md-offset-2 col-xs-12 col-sm-12 col-md-8 col-lg-8 mt-90">
            <div class="modify-w-form contact post">
                <h3 style="text-align: center; color:#FF660F">
                    Xin chúc mừng bạn đăng ký dự thi thành công
                </h3>
                <h4>
                    <strong>Thông tin dự thi</strong>
                </h4>

                <p>
                    <strong>Số Báo Danh:</strong> @Model.IdentificationNumber
                </p>
                <p>
                    <strong>Họ và Tên Phụ Huynh:</strong> @Model.ParentName
                </p>
                <p>
                    <strong>Họ và Tên Con:</strong> @Model.ChildName
                </p>
                @*<p>
                    <strong>@Model.GradeName</strong>
                </p>*@
                <p>
                    <strong>Trường:</strong> @Model.SchoolName
                </p>
                <p>
                    <strong>Địa Chỉ:</strong> @Model.Address @Model.DistrictName @Model.CityName
                </p>
                <h4>Đề thi đầu tiên của em</h4>
                <p>
                    " Em hãy giúp người khác hiểu và thuộc thể lệ cuộc thi 5 Phút Thuộc Bài chỉ trong vòng 5 phút dựa trên Sơ Đồ Tư Duy "
                </p>
                <p><strong>Ngày bắt đầu nộp bài:</strong> 22/7/2021</p>
                <p><strong>Hạn chót nộp bài:</strong> 23:59 Chủ Nhật, ngày 25/07/2021</p>
                <div class="text-center"><a href="@Url.Action("Index","NamPhutThuocBai")" class="btn btn-primary">Quay lại cuộc thi</a></div>
            </div>
        </div>
    </div>
</div>

GCSOFT.MVC.STNHD/Views/NamPhutThuocBai/_MenuThiSinh.cshtml
<a id="btnVideos" class="btn btn-sign-up" href="@Url.Action("BaiDuThi", "NamPhutThuocBai")" style="position: initial; margin-top: 10px; margin-right: 30px;">Danh Sách Đề Thi</a>
<a id="btnThongTinThiSinh" class="btn btn-sign-up" href="@Url.Action("index", "NamPhutThuocBai")" style="position: initial; margin-top: 10px; margin-right: 30px;">Trang Chủ Cuộc Thi</a>

GCSOFT.MVC.STNHD/Views/NamPhutThuocBai/profile.cshtml
@{
    ViewBag.Title = "Thông tin học viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row" style="padding-top: 20px;">
        <div class="col-lg-12 col-md-12 col-sm-12 text-center">
            <a id="btnVideos" class="btn btn-sign-up" href="@Url.Action("Exam", "NamPhutThuocBai")" style="position: initial; margin-top: 10px; margin-right: 30px;">Danh Sách Đề Thi</a>
            <a id="btnDocument" class="btn btn-sign-up" href="@Url.Action("profile", "NamPhutThuocBai")" style="position: initial; margin-top: 10px; margin-right: 30px;">Thông tin học viên</a>
            <a id="btnThongTinThiSinh" class="btn btn-sign-up" href="@Url.Action("index", "NamPhutThuocBai")" style="position: initial; margin-top: 10px; margin-right: 30px;">Trang Chủ Cuộc Thi</a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="text-center"><h3 class="h-title" style="margin-bottom: 29px; color: #337ab7; margin-top: 35px;">Danh Sách Đề Thi</h3></div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="post">
                <div class="post-top">
                    <div class="media">
                        <div class="media-body">
                            <h4 class="media-heading" style="color: #FF660F;">Đề thi tuần ngày 22/7</h4>
                            <p>Ngày bắt đầu: 22/7/2021 - Ngày hết hạn: 23:59 Chủ Nhật, ngày 25/07/2021</p>
                        </div>
                    </div>
                    <p class="txt">Em hãy giúp người khác hiểu và thuộc thể lệ cuộc thi 5 Phút Thuộc Bài chỉ trong vòng 5 phút dựa trên Sơ Đồ Tư Duy</p>
                    <div class="text-left post-btn"><a href="javascript:void(0);">Ngày bắt đầu nộp bài: 22/7/2021</a></div>
                </div>
                <div class="clear-both"></div>
            </div>
            <div class="clear-both"></div>
        </div>
    </div>
</div>